"""Use Python's utcnow for HighFive created_at

Revision ID: 2e28f5d9003d
Revises: 2ffc08943069
Create Date: 2024-09-03 18:08:06.267676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e28f5d9003d'
down_revision = '2ffc08943069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('high_five', schema=None) as batch_op:
        batch_op.drop_constraint('fk_high_five_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_high_five_post_id_forum_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_high_five_post_id_forum_post'), 'forum_post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_high_five_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('high_five', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_high_five_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_high_five_post_id_forum_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_high_five_post_id_forum_post', 'forum_post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_high_five_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
