"""Add last_login to User model

Revision ID: 757668456b93
Revises: 2e28f5d9003d
Create Date: 2024-09-11 17:42:49.754969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757668456b93'
down_revision = '2e28f5d9003d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
